# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "XhubTemplate.xcodeproj")
    build_app(workspace: "XhubTemplate.xcworkspace", scheme: "XhubTemplate")
    commit_version_bump(message: 'bump build')
    push_to_git_remote
  end
end