# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Build and archive iOS app"
  lane :build do
    increment_build_number
    build_app(
      scheme: "YourAppScheme",
      workspace: "YourApp.xcworkspace",
      configuration: "Release",
      output_directory: "build",
      output_name: "YourApp.ipa"
    )
  end
end
