name: "Build Android app"

on:
 workflow_dispatch:
    # can add push and pull_request here 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Npm Install
        run: |
             cd ./packages/app-mobile/
             npm i -g corepack
             npm install
             
      # Debug build steps
      - name: Build application (Debug)
        run: |
             cd ./packages/app-mobile/android
             ./gradlew assembleDebug
             
      - name: Upload application (Debug)
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: ./packages/app-mobile/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3

      # Release build steps
      - name: Build application (Release)
        run: |
             cd ./packages/app-mobile/android
             ./gradlew assembleRelease
             
      - name: Upload application (Release)
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ./packages/app-mobile/android/app/build/outputs/apk/release/app-release.apk
          retention-days: 3
